version: '2.1'
services:
  backend:
    image: ruby:2.3
    container_name: graphql-backend
    volumes:
      - .:/graphql-backend
    ports:
      - '3000:3000'
    command: >
      bash -c 'cd /graphql-backend && bundle install && rails db:setup && rails db:migrate && rails s'

  db:
    image: postgres:9.5-alpine
    container_name: graphql-database
